apiVersion: v1
kind: ConfigMap
metadata:
  name: hodor-config
data:
  config.json: |-
    {
        "rules": {
            "example.com:8080": {
                "config": {
                    "clientID": "",
                    "clientSecret": "",
                    "endpoint": {
                        "authURL": "",
                        "tokenURL": ""
                    },
                    "redirectURL": "http://example.com:8080/callback",
                    "scopes": [
                        "read_user",
                        "email"
                    ]
                }
            }
        },
        "verify_path": "/",
        "callback_path": "/callback"
    }
