apiVersion: v1
kind: Service
metadata:
  name: hodor
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: AuthService
      name: authentication
      auth_service: hodor
      path_prefix: "verify"
      proto: http
      allowed_request_headers:
        - Host
spec:
  selector:
    app: hodor
  ports:
  - port: 80
    targetPort: 8080
