# https://raw.githubusercontent.com/heptio/contour/master/deployment/example-workload/kuard.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: kuad_mapping
      host: example.com:8080
      prefix: /
      service: kuard:80
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
  sessionAffinity: None
  type: ClusterIP
